### ISSUE TITLE
Estabilidad API alertas

### ISSUE THREAD

**Issue by pgallardor** [alercebroker/web-services#112]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/ztf_api/issues/121
- [ ] https://github.com/alercebroker/ztf_api/issues/113
- [ ] https://github.com/alercebroker/ztf_api/issues/117
- [ ] https://github.com/alercebroker/ztf_api/issues/114
```

**Comment by dirodriguezm** [comment]
Puede que haya algún problema de memory leak.

Ver este ejemplo de uso de CPU y Memory un pod recién creado vs otros de hace 20hrs

```
alerts-api-75c4877859-pmlqn   3m           87Mi            
alerts-api-75c4877859-skgx5   8m           604Mi           
alerts-api-75c4877859-zbfrq   8m           635Mi           
```

**Comment by dirodriguezm** [comment]
Después de aplicar #113, el problema de memoria parece seguir ocurriendo, por lo que no están relacionados.
