### ISSUE TITLE
Refactorización en microservicios en monorepo

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/web-services#114]
Cambio de capa de presentacion del API de Flask a FastAPI (gracias Arquitectura Limpia)

Pero también hace falta completar https://github.com/alercebroker/ralidator-fastapi

```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/ztf_api/issues/131
- [ ] https://github.com/alercebroker/ztf_api/issues/130
- [ ] https://github.com/alercebroker/ztf_api/issues/129
- [ ] https://github.com/alercebroker/ztf_api/issues/128
- [ ] https://github.com/alercebroker/ztf_api/issues/127
- [ ] https://github.com/alercebroker/ztf_api/issues/126
- [ ] https://github.com/alercebroker/ztf_api/issues/125
- [ ] https://github.com/alercebroker/web-services/issues/149
- [ ] https://github.com/alercebroker/web-services/issues/154
- [ ] https://github.com/alercebroker/web-services/issues/155
- [ ] https://github.com/alercebroker/web-services/issues/171
```
