### ISSUE TITLE
Profile memory leak

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/web-services#121]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/ztf_api/issues/124
- [ ] https://github.com/alercebroker/ztf_api/issues/123
- [ ] https://github.com/alercebroker/ztf_api/issues/136
```

**Comment by dirodriguezm** [comment]
Lo primero sería revisar el módulo astro_object, que usa tanta ram incluso cuando no hay requests hacia ese recurso.
