### ISSUE TITLE
Refactorizar Lightcurve a FastAPI

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/web-services#130]
```[tasklist]
### Tasks
- [x] Endpoint detections
- [x] Endpoint non_detections
- [x] Endpoint light curve
- [x] Dockerfile
- [ ] #125
- [ ] https://github.com/alercebroker/ztf_api/issues/138
- [ ] https://github.com/alercebroker/ztf_api/issues/139
- [ ] https://github.com/alercebroker/ztf_api/issues/140
- [ ] https://github.com/alercebroker/ztf_api/issues/141
- [ ] https://github.com/alercebroker/ztf_api/issues/142
- [ ] https://github.com/alercebroker/web-services/issues/172
- [ ] https://github.com/alercebroker/web-services/issues/175
```
