### ISSUE TITLE
Refactorizar Astro Object a FastAPI

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/web-services#131]
```[tasklist]
### Tasks
- [x] Endpoint object list
- [x] Endpoint object by id
- [x] Endpoint limit values
- [x] Métricas de uso con prometheus
- [x] Dashboard grafana con métricas de uso
- [x] Log error 500 a cloud watch
- [x] Dashboard grafana con logs 500
- [x] Deployment con chart desde monorepo
```
