### ISSUE TITLE
Lightcurve Service Multistream

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/web-services#178]
# Descripción

La idea de este servicio es proveer acceso a la curva de luz tanto de ZTF como de ATLAS. Existen dos componentes para este servicio: el componente REST que responde en JSON y un componente HTML que retorna HTML.

## Historias de usuario

1. Como astrónom@ con acceso a ATLAS, quiero acceder a la curva de luz de ZTF y ATLAS usando un object id de ZTF
2. Como astrónom@ con acceso a ATLAS, quiero acceder a la curva de luz de ZTF y ATLAS usando un object id de ATLAS
3. Como astrónom@ con acceso a ATLAS, quiero acceder a la curva de luz de ZTF y ATLAS usando un object id de ALeRCE
4. Como astrónom@ con acceso a ATLAS, quiero acceder a la curva de luz de ATLAS usando un object id de ATLAS
3. Como astrónom@ con acceso a ATLAS, quiero acceder a la curva de luz de ATLAS usando un object id de ALeRCE
5. Como astrónom@ sin acceso a ATLAS, quiero acceder a la curva de luz de ZTF usando un object id de ZTF
6. Como astrónom@ sin acceso a ATLAS, quiero acceder a la curva de luz de ZTF usando un object id de ALeRCE

## Componente REST
Esta es la interfaz típica para acceso programático. Diferentes clientes HTTP se van a conectar a estos endpoints para acceder a la curva de luz, detecciones y no detecciones.

La respuesta debe ser siempre JSON y los endpoints deben recibir parámetros para object id y para survey id.

## Componente HTML
La clave de este componente es el uso de [HTMX](https://htmx.org). Las aplicaciones web (Explorer, Hunter, etc) se conectan a estos endpoints para recibir HTML (y javascript cuando corresponda) mediante HTMX.

Caso de ejemplo: El layout en el explorer comienza con un `div` vacío que tiene un atributo de HTMX indicando que gatille una request cuando el div carga en el navegador. HTMX entonces realiza una request al endpoint `/plot/ZTF20aaelulu?plot=apparent` y este retorna HTML + JS con el gráfico que incluye un botón que a su vez posee un atributo HTMX para realizar una request mediante HTMX a un endpoint `/plot/ZTF20aaelulu?plot=folded`. De esta forma obtenemos la interactividad de una SPA pero con la simpleza de una aplicación SSR.

![Image](https://github.com/alercebroker/web-services/assets/18015991/8b77d0c6-af39-4528-8358-7227fe541772)

### Stack para componente HTML
La idea es no diverger tanto de lo que ya estábamos usando, pero simplificando el stack donde se pueda. La propuesta es la siguiente:

- ECharts JS para gráficos
- HTML puro y TailwindCSS para botones, radio buttons, etc
- HTMX para "interactividad"

```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/web-services/issues/183
- [ ] https://github.com/alercebroker/web-services/issues/184
- [ ] https://github.com/alercebroker/web-services/issues/185
- [ ] https://github.com/alercebroker/ztf_explorer/issues/409
- [ ] https://github.com/alercebroker/web-services/issues/191
- [ ] https://github.com/alercebroker/web-services/issues/186
- [ ] https://github.com/alercebroker/web-services/issues/187
- [ ] https://github.com/alercebroker/web-services/issues/188
- [ ] https://github.com/alercebroker/web-services/issues/189
- [ ] https://github.com/alercebroker/sn_hunter/issues/75
- [ ] https://github.com/alercebroker/web-services/issues/236
- [ ] https://github.com/alercebroker/web-services/issues/237
- [ ] https://github.com/alercebroker/web-services/issues/238
- [ ] https://github.com/alercebroker/pipeline/issues/289
- [ ] https://github.com/alercebroker/web-services/issues/246
- [ ] https://github.com/alercebroker/ztf_explorer/issues/415
- [ ] https://github.com/alercebroker/web-services/issues/248
- [ ] https://github.com/alercebroker/ztf_explorer/issues/416
- [ ] https://github.com/alercebroker/web-services/issues/249
- [ ] https://github.com/alercebroker/web-services/issues/253
- [ ] https://github.com/alercebroker/web-services/issues/254
- [ ] https://github.com/alercebroker/web-services/issues/257
```
