### ISSUE TITLE
Object Service Multistream

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/web-services#205]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/web-services/issues/206
- [ ] https://github.com/alercebroker/ztf_explorer/issues/411
- [ ] https://github.com/alercebroker/ztf_explorer/issues/412
- [ ] https://github.com/alercebroker/web-services/issues/214
- [ ] https://github.com/alercebroker/web-services/issues/215
- [ ] https://github.com/alercebroker/web-services/issues/216
- [ ] https://github.com/alercebroker/web-services/issues/217
- [ ] https://github.com/alercebroker/ztf_explorer/issues/413
- [ ] https://github.com/alercebroker/sn_hunter/issues/76
- [ ] https://github.com/alercebroker/ztf_explorer/issues/414
- [ ] https://github.com/alercebroker/alerce_client/issues/37
- [ ] https://github.com/alercebroker/alerce_client/issues/38
- [ ] https://github.com/alercebroker/alerce_reporter_front/issues/17
- [ ] https://github.com/alercebroker/alerce_users_api/issues/64
- [ ] https://github.com/alercebroker/forecast_api/issues/6
``` 

# Description
Web service that provides object searches accross multiple surveys and/or databases by specified filters (to be defined)

<a id="org87bf899"></a>

# Endpoints

<a id="org481ad99"></a>

## JSON

<a id="org0809df0"></a>

### `/object/oid/`

-   URL Params: oid
-   Retrieves everything in the object root level attributes plus the following

<a id="org5ddec13"></a>

### `/objects/?[filters]`

<a id="orgf268ef9"></a>

## HTMX

<a id="orga201a55"></a>

### `/object-form/`

<a id="org147f795"></a>

### `/object-result/`

<a id="orgcfb0909"></a>

### `/object-info-card/`

<a id="org9e46a80"></a>

# Dependencies

![Image](https://github.com/alercebroker/web-services/assets/18015991/ef96f069-71d6-4901-85ea-0dd6133d075c)

-   [Python Client](https://github.com/alercebroker/alerce_client)
    -   Wrappers para los endpoints JSON
        -   query<sub>object</sub>(oid)
        -   query<sub>objects</sub>(\*\*filters)
-   [Explorer](https://github.com/alercebroker/ztf_explorer)
    -   Formulario de filtros -> /object-form
    -   Tabla de resultados -> /object-result
    -   Card con información del objeto -> /object-info-card
-   [SNHunter](https://github.com/alercebroker/sn_hunter)
    -   Tabla de resultados -> /object-result
-   [User Services](https://github.com/alercebroker/alerce_users_api)
    -   Aplicación de reportes usa [Python Client](https://github.com/alercebroker/alerce_client) -> /object/oid
        método csv<sub>reports</sub> usa ndet, firstmjd, lastmjd
        este se llama desde reporter
-   [Forecast API](https://github.com/alercebroker/forecast_api)
    -   Usa [Python Client](https://github.com/alercebroker/alerce_client)
        -   /object/oid
            -   usa firstmjd
        -   /detections/oid
            No es retrocompatible porque usa una versión vieja del feature extractor.
            Se podría actualizar para usar pipeline/libs/lc<sub>classifier</sub>
        -   /features/oid
            busca las siguientes features:
                  "SPM_t0",
                  "SPM_chi",
                  "SPM_gamma",
                  "SPM_beta",
                  "SPM_A",
                  "SPM_tau_rise",
                  "SPM_tau_fall",
          
-   [Reports Frontend](https://github.com/alercebroker/alerce_reporter_front)
    -   Hace request a /object/oid
        -   usa ndet, firstmjd
    -   Indirectamente a través de [User Services](https://github.com/alercebroker/alerce_users_api) que usa [Python Client](https://github.com/alercebroker/alerce_client) a /object/oid
