### ISSUE TITLE
Mejoras CI/CD

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/web-services#235]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/web-services/issues/232
- [ ] https://github.com/alercebroker/web-services/issues/234
- [ ] https://github.com/alercebroker/web-services/issues/233
- [ ] https://github.com/alercebroker/web-services/issues/241
```
