### ISSUE TITLE
Arreglar búsqueda de lightcurve ATLAS

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/web-services#257]
```[tasklist]
### Tasks
- [x] Mejorar los tests para que sean más claros los casos de prueba (Pair Prog)
- [x] Encontrar el bug de la búsqueda (Diego)
- [x] Corregir bug (Diego)
```

**Comment by dirodriguezm** [comment]
Se definieron 5 casos de prueba para las búsquedas de curva de luz:

1. ZTF 1 solo oid por aid
    Si busco por `survey_id==atlas` resultado vacío ; si no resultado ztf
2. ZTF muchos oid por aid
    Si busco por `survey_id==atlas` resultado vacío ; si no resultado ztf
3. ATLAS 1 solo oid por aid
    Si busco por `survey_id==ztf` resultado vacío ; si no resultado atlas
4. ATLAS muchos oid por aid
    Si busco por `survey_id==ztf` resultado vacío ; si no resultado atlas
5. ZTF y ATLAS oid en el mismo aid
    Si busco por `survey_id==ztf` resultado detecciones de ztf
    Si busco por `survey_id==atlas` resultado detecciones de atlas
    Si busco por `survey_id==all` resultado todas las detecciones

Caso 1 y 2 ya están probados
